# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            walter
tagline:          'My life, in blog form'
description:      'My life, in blog form'
url:              http://walteranderson.me
baseurl:          /

author:
  name:           'Walter Anderson'
  url:            https://twitter.com/walteranderson

paginate:         5

# Custom vars

twitter:
  profile:        https://twitter.com/walteranderson

linkedin:
  profile:        https://linkedin.com/in/walteranderson19

github:
  profile:        https://github.com/walteranderson
  repo:           https://github.com/walteranderson/walteranderson.github.io