# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            walter
tagline:          'A blog by the same name'
description:      ''
url:              http://walteranderson.me
baseurl:          /

author:
  name:           'Walter Anderson'
  url:            https://twitter.com/walteranderson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/walteranderson/walteranderson.github.io